// src/react/components/Notification/Notification.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import type { NotificationProps } from '../../../core/components/notification.react.types';
import Icon from '../Icon';
import '../../../components/Notification/style.css';

const typeIconNameMap: Record<string, string> = {
  success: 'circle-check',
  info: 'circle-info',
  warning: 'circle-exclamation',
  danger: 'circle-xmark',
};

interface InternalNotificationProps extends NotificationProps {
  getLastBottomOffset: () => number;
  onUpdateHeight: (height: number) => void;
}

export default function Notification({
  title,
  message,
  duration = 3000,
  showClose = true,
  type = 'info',
  onDestory,
  offset = 20,
  zIndex,
  icon,
  getLastBottomOffset,
  onUpdateHeight,
}: InternalNotificationProps) {
  const [visible, setVisible] = useState(false);
  const notifyRef = useRef<HTMLDivElement>(null);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const lastOffset = getLastBottomOffset();
  const topOffset = offset + lastOffset;

  const iconName = type ? typeIconNameMap[type] || icon : icon;

  const startTimer = useCallback(() => {
    if (duration === 0) return;
    timerRef.current = setTimeout(() => {
      setVisible(false);
    }, duration);
  }, [duration]);

  const clearTimer = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  };

  useEffect(() => {
    setVisible(true);
    startTimer();

    const handleKeydown = (e: KeyboardEvent) => {
      if (e.code === 'Escape') {
        setVisible(false);
      }
    };
    document.addEventListener('keydown', handleKeydown);
    return () => {
      clearTimer();
      document.removeEventListener('keydown', handleKeydown);
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Measure height after becoming visible
  useEffect(() => {
    if (visible && notifyRef.current) {
      const height = notifyRef.current.getBoundingClientRect().height;
      onUpdateHeight(height);
    }
  }, [visible]); // eslint-disable-line react-hooks/exhaustive-deps

  // Destroy after leave animation
  useEffect(() => {
    if (!visible) {
      const timer = setTimeout(() => {
        onDestory();
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [visible, onDestory]);

  return (
    <div
      className={[
        'vk-notification',
        type ? `vk-notification--${type}` : '',
        showClose ? 'is-close' : '',
        visible ? '' : 'vk-notification-fade-leave-to',
      ]
        .filter(Boolean)
        .join(' ')}
      role="alert"
      ref={notifyRef}
      style={{
        top: `${topOffset}px`,
        zIndex,
        opacity: visible ? 1 : 0,
        transition: 'opacity 0.3s, transform 0.3s, right 0.3s, top 0.4s',
      }}
      onMouseEnter={clearTimer}
      onMouseLeave={startTimer}
    >
      {iconName && <Icon name={iconName} className="vk-notification__icon" />}
      <div className="vk-notification__text">
        <div className="vk-notification__title">{title}</div>
        <div className="vk-notification__content">{message}</div>
      </div>
      {showClose && (
        <div className="vk-notification__close">
          <Icon
            name="xmark"
            onClick={(e) => {
              e.stopPropagation();
              setVisible(false);
            }}
          />
        </div>
      )}
    </div>
  );
}

// src/vue/components/Notification/Notification.vue
<template>
  <Transition
    :name="`vk-notification-${transitionName}`"
    @after-leave="destroyComponent"
    @enter="updateHeight"
  >
    <div
      class="vk-notification"
      v-show="visible"
      :class="{
        [`vk-notification--${type}`]: type,
        'is-close': showClose
      }"
      role="alert"
      ref="notifyRef"
      :style="cssStyle"
      @mouseenter="clearTimer"
      @mouseleave="startTimer"
    >
      <Icon :icon="iconName" v-if="iconName" class="vk-notification__icon"/>
      <div class="vk-notification__text">
        <div class="vk-notification__title">
          {{title}}
        </div>
        <div class="vk-notification__content">
          <slot>
            <RenderVnode :vNode="message" v-if="message" />
          </slot>
        </div>
      </div>
      <div class="vk-notification__close" v-if="showClose">
        <Icon @click.stop="visible = false" icon="xmark"/>
      </div>
    </div>
  </Transition>
</template>
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import type { NotificationProps } from '@/components/Notification/types'
import { getLastBottomOffset } from './method'
import RenderVnode from '../Common/RenderVnode'
import Icon from '../Icon.vue'
import useEventListener from '@/hooks/useEventListener'
import { typeIconNameMap } from '../../../../utils'
import '@/components/Notification/style.css'

const props = withDefaults(defineProps<NotificationProps>(), {
  type: 'info',
  duration: 3000,
  offset: 20,
  transitionName: 'fade',
  showClose: true
})
const visible = ref(false)
const notifyRef = ref<HTMLDivElement>()
const iconName = computed(() => {
  if (!props.type) return props.icon
  return typeIconNameMap[props.type] || props.icon
})

const height = ref(0)
const lastOffset = computed(() => getLastBottomOffset(props.id))
const topOffset = computed(() => props.offset + lastOffset.value)
const bottomOffset = computed(() => height.value + topOffset.value)
const cssStyle = computed(() => ({
  top: topOffset.value + 'px',
  zIndex: props.zIndex
}))
let timer: any
function startTimer() {
  if (props.duration === 0) return
  timer = setTimeout(() => {
    visible.value = false
  }, props.duration)
}
function clearTimer() {
  clearTimeout(timer)
}
onMounted(async () => {
  visible.value = true
  startTimer()
})
function keydown(e: Event) {
  const event = e as KeyboardEvent
  if (event.code === 'Escape') {
    visible.value = false
  }
}
useEventListener(document, 'keydown', keydown)

function destroyComponent() {
  props.onDestory()
}
function updateHeight() {
  height.value = notifyRef.value!.getBoundingClientRect().height
}
defineExpose({
  visible,
  bottomOffset
})
</script>
