// src/react/components/Button.tsx
import React from 'react';
import type { ButtonProps } from '../../core/components/button.react.types';
import Icon from './Icon';

export default function Button({
                                   children,
                                   onClick,
                                   disabled,
                                   type = 'primary',
                                   icon,
                                   loading = false,
                               }: ButtonProps) {
    return (
        <button
            className={`vk-button vk-button--${type} ${loading ? 'is-loading' : ''}`}
            disabled={disabled || loading}
            onClick={onClick}
            data-testid="button"
        >
            {loading && <Icon name="spinner" spin data-testid="button-loading-icon" />}
            {!loading && icon && <span data-testid="button-icon">{icon}</span>}
            <span data-testid="button-text">{children}</span>
        </button>
    );
}

// src/components/Button/Button.vue
<template>
  <button
    ref="_ref"
    class="vk-button"
    :class="{
      [`vk-button--${type}`]: type,
      [`vk-button--${size}`]: size,
      'is-plain': plain,
      'is-round': round,
      'is-circle': circle,
      'is-disabled': disabled,
      'is-loading': loading
    }"
    :disabled="disabled || loading"
    :autofocus="autofocus"
    :type="nativeType"
  >
    <Icon icon="spinner" spin v-if="loading" />
    <Icon :icon="icon" v-if="icon" />
    <span>
      <slot />
    </span>
  </button>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import type { ButtonProps } from './types'
import Icon from '../Icon/Icon.vue'
// import { buttonProps } from './types'
defineOptions({
  name: 'VkButton'
})

withDefaults(defineProps<ButtonProps>(), {
  nativeType: 'button',
})

const _ref = ref<HTMLButtonElement>()

defineExpose({
  ref: _ref
})
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
