// src/react/components/Form/FormItem.tsx
import React, { createContext, useState, useRef, useEffect, useContext, useMemo } from 'react';
import Schema from 'async-validator';
import type {
  FormItemProps,
  FormItemContextType,
  ValidateStatusProp,
  FormValidateFailure,
} from '../../../core/components/form.react.types';
import { FormContext } from './Form';

export const FormItemContext = createContext<FormItemContextType | null>(null);

export default function FormItem({ label, prop, children }: FormItemProps) {
  const formContext = useContext(FormContext);
  const [validateStatus, setValidateStatus] = useState<ValidateStatusProp>({
    state: 'init',
    errorMsg: '',
    loading: false,
  });
  const initialValueRef = useRef<any>(null);
  const contextRef = useRef<FormItemContextType | null>(null);

  const innerValue = useMemo(() => {
    const model = formContext?.model;
    if (model && prop && model[prop] != null) {
      return model[prop];
    }
    return null;
  }, [formContext?.model, prop, formContext?.model?.[prop ?? '']]);

  const itemRules = useMemo(() => {
    const rules = formContext?.rules;
    if (rules && prop && rules[prop]) {
      return rules[prop];
    }
    return [];
  }, [formContext?.rules, prop]);

  const getTriggeredRules = (trigger?: string) => {
    if (itemRules) {
      return itemRules.filter((rule) => {
        if (!rule.trigger || !trigger) return true;
        return rule.trigger === trigger;
      });
    }
    return [];
  };

  const isRequired = itemRules.some((rule) => rule.required);

  const validate = async (trigger?: string) => {
    const modelName = prop;
    const triggeredRules = getTriggeredRules(trigger);
    if (triggeredRules.length === 0) {
      return true;
    }
    if (modelName) {
      const validator = new Schema({
        [modelName]: triggeredRules,
      });
      setValidateStatus((s) => ({ ...s, loading: true }));
      return validator
        .validate({ [modelName]: innerValue })
        .then(() => {
          setValidateStatus({ state: 'success', errorMsg: '', loading: false });
        })
        .catch((e: FormValidateFailure) => {
          const { errors } = e;
          setValidateStatus({
            state: 'error',
            errorMsg: errors && errors.length > 0 ? errors[0].message || '' : '',
            loading: false,
          });
          return Promise.reject(e);
        });
    }
  };

  const clearValidate = () => {
    setValidateStatus({ state: 'init', errorMsg: '', loading: false });
  };

  const resetField = () => {
    clearValidate();
    const model = formContext?.model;
    if (model && prop && model[prop] != null) {
      model[prop] = initialValueRef.current;
    }
  };

  // Create a stable context object
  if (!contextRef.current) {
    contextRef.current = {
      validate,
      prop: prop || '',
      clearValidate,
      resetField,
    };
  }
  // Keep the methods up-to-date
  contextRef.current.validate = validate;
  contextRef.current.clearValidate = clearValidate;
  contextRef.current.resetField = resetField;

  useEffect(() => {
    if (prop) {
      initialValueRef.current = innerValue;
      formContext?.addField(contextRef.current!);
    }
    return () => {
      if (contextRef.current) {
        formContext?.removeField(contextRef.current);
      }
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <FormItemContext.Provider value={contextRef.current}>
      <div
        className={[
          'vk-form-item',
          validateStatus.state === 'error' ? 'is-error' : '',
          validateStatus.state === 'success' ? 'is-success' : '',
          validateStatus.loading ? 'is-loading' : '',
          isRequired ? 'is-required' : '',
        ]
          .filter(Boolean)
          .join(' ')}
      >
        {label && (
          <label className="vk-form-item__label">{label}</label>
        )}
        <div className="vk-form-item__content">
          {children}
          {validateStatus.state === 'error' && (
            <div className="vk-form-item__error-msg">{validateStatus.errorMsg}</div>
          )}
        </div>
      </div>
    </FormItemContext.Provider>
  );
}

// src/components/Form/FormItem.vue
<template>
  <div 
    class="vk-form-item"
    :class="{
      'is-error': validateStatus.state === 'error',
      'is-success': validateStatus.state === 'success',
      'is-loading': validateStatus.loading,
      'is-required': isRequired
    }"
  >
    <label class="vk-form-item__label">
      <slot name="label" :label="label">
        {{label}}
      </slot>
    </label>
    <div class="vk-form-item__content">
      <slot :validate="validate"/>
      <div class="vk-form-item__error-msg" v-if="validateStatus.state === 'error'">
        {{validateStatus.errorMsg}}
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { inject, computed, reactive, provide, onMounted, onUnmounted } from 'vue'
import Schema from 'async-validator'
import { isNil } from 'lodash-es'
import { formContextKey, formItemContextKey } from './types'
import type { FormItemProps, FormValidateFailure, FormItemContext, ValidateStatusProp, FormItemInstance } from './types'
defineOptions({
  name: 'VkFormItem'
})
const props = defineProps<FormItemProps>()

const formContext = inject(formContextKey)
const validateStatus: ValidateStatusProp = reactive({
  state: 'init',
  errorMsg: '',
  loading: false
})
let initialValue: any = null
const innerValue = computed(() => {
  const model = formContext?.model
  if (model && props.prop && !isNil(model[props.prop])) {
    return model[props.prop]
  } else {
    return null
  }
})
const itemRules = computed(() => {
  const rules = formContext?.rules
  if (rules && props.prop && rules[props.prop]) {
    return rules[props.prop]
  } else {
    return []
  }
})
const getTriggeredRules = (trigger?: string) => {
  const rules = itemRules.value
  if (rules) {
    return rules.filter(rule => {
      if (!rule.trigger || !trigger) return true
      return rule.trigger && rule.trigger === trigger
    })
  } else {
    return []
  }
}
const isRequired = computed(() => {
  return itemRules.value.some(rule => rule.required)
})
const validate = async (trigger?: string) => {
  const modelName = props.prop
  const triggeredRules = getTriggeredRules(trigger)
  if (triggeredRules.length === 0) {
    return true
  }
  if (modelName) {
    const validator = new Schema({
      [modelName]: triggeredRules
    })
    validateStatus.loading = true
    return validator.validate({ [modelName]: innerValue.value })
      .then(() => {
        validateStatus.state = 'success'
      })
      .catch((e: FormValidateFailure) => {
        const { errors } = e
        validateStatus.state = 'error'
        validateStatus.errorMsg = (errors && errors.length > 0) ? errors[0].message || '' : ''
        console.log(e.errors)
        return Promise.reject(e)
      })
      .finally(() => {
        validateStatus.loading = false
      })
  }
}
const clearValidate = () => {
  validateStatus.state = 'init'
  validateStatus.errorMsg = ''
  validateStatus.loading = false
}
const resetField = () => {
  clearValidate()
  const model = formContext?.model
  if (model && props.prop && !isNil(model[props.prop])) { 
    model[props.prop] = initialValue
  }
}
const context: FormItemContext = {
  validate,
  prop: props.prop || '',
  clearValidate,
  resetField
}
provide(formItemContextKey, context)

onMounted(() => {
  if (props.prop) {
    formContext?.addField(context)
    initialValue = innerValue.value
  }
})
onUnmounted(() => {
  formContext?.removeField(context)
})
defineExpose<FormItemInstance>({
  validateStatus,
  validate,
  resetField,
  clearValidate
})
</script>
