// src/vue/components/Dropdown/Dropdown.vue
<template>
  <div class="vk-dropdown">
    <Tooltip
        :trigger="trigger"
        :placement="placement"
        :popper-options="popperOptions"
        :open-delay="openDelay"
        :close-delay="closeDelay"
        :manual="manual"
        @visible-change="visibleChange"
        ref="tooltipRef"
    >
      <slot />
      <template #content>
        <ul class="vk-dropdown__menu">
          <template v-for="item in menuOptions" :key="item.key">
            <li v-if="item.divided" role="separator" class="divided-placeholder" />
            <li
                class="vk-dropdown__item"
                @click="itemClick(item)"
                :class="{ 'is-disabled': item.disabled, 'is-divided': item.divided }"
                :id="`dropdown-item-${item.key}`"
            >
              <RenderVnode :vNode="item.label" />
            </li>
          </template>
        </ul>
      </template>
    </Tooltip>
  </div>
</template>

<script setup lang="ts">
import Tooltip from '../Tooltip/Tooltip.vue'
import RenderVnode from '../Common/RenderVnode'
import { useDropdownLogic } from '../../core/components/dropdown.logic'
import type { DropdownProps, DropdownEmits } from '../../core/components/dropdown.types'

const props = withDefaults(defineProps<DropdownProps>(), { hideAfterClick: true })
const emit = defineEmits<DropdownEmits>()

const { tooltipRef, visibleChange, itemClick, expose } = useDropdownLogic(props, emit)

defineExpose(expose)
</script>

// src/react/components/Dropdown/Dropdown.tsx
import React, { useRef } from 'react'
import type { DropdownProps } from '../../core/components/dropdown.types'
import { useDropdownLogic } from '../../core/components/dropdown.logic'
import Tooltip from '../Tooltip'
import '../../core/styles/dropdown.css'

const Dropdown: React.FC<DropdownProps> = (props) => {
    const { tooltipRef, visibleChange, itemClick } = useDropdownLogic(props)

    return (
        <div className="vk-dropdown">
            <Tooltip
                trigger={props.trigger}
                placement={props.placement}
                openDelay={props.openDelay}
                closeDelay={props.closeDelay}
                manual={props.manual}
                ref={tooltipRef}
                onVisibleChange={visibleChange}
            >
                {props.children}
                <ul className="vk-dropdown__menu">
                    {props.menuOptions.map(item => (
                        <React.Fragment key={item.key}>
                            {item.divided && <li role="separator" className="divided-placeholder" />}
                            <li
                                id={`dropdown-item-${item.key}`}
                                className={`vk-dropdown__item ${item.disabled ? 'is-disabled' : ''} ${item.divided ? 'is-divided' : ''}`}
                                onClick={() => itemClick(item)}
                            >
                                {item.label}
                            </li>
                        </React.Fragment>
                    ))}
                </ul>
            </Tooltip>
        </div>
    )
}

export default Dropdown
