// src/react/components/CodeBlock/CodeBlock.tsx
import { useState, useCallback, useMemo, useRef, useEffect, memo } from 'react'
import type { CodeBlockProps } from '../../../core/components/code-block.types'
import { copyToClipboard, generateLineNumbers, highlightCode, wrapLines } from '../../../core/components/code-block.logic'
import '../../../components/CodeBlock/style.css'

export const CodeBlock = memo(function CodeBlock({
  code = '',
  language = '',
  showLineNumbers = false,
  copyable = true,
  maxHeight = '500px',
  scrollable = true,
  wrap = false,
  theme = 'dark',
  highlightLines,
  title,
  copyText = '复制',
  copiedText = '已复制',
}: CodeBlockProps) {
  const [copied, setCopied] = useState(false)
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const lineNumbers = useMemo(() => generateLineNumbers(code), [code])
  const highlightedHtml = useMemo(() => {
    const html = highlightCode(code, language)
    return highlightLines?.length ? wrapLines(html, highlightLines) : html
  }, [code, language, highlightLines])

  useEffect(() => {
    return () => {
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current)
    }
  }, [])

  const handleCopy = useCallback(async () => {
    try {
      await copyToClipboard(code)
      setCopied(true)
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current)
      copyTimerRef.current = setTimeout(() => setCopied(false), 2000)
    } catch {
      // clipboard API may fail
    }
  }, [code])

  return (
    <div className={`vk-code-block${theme === 'light' ? ' vk-code-block--light' : ''}`} data-testid="code-block">
      {(title || language || copyable) && (
        <div className="vk-code-block__header">
          {(title || language) ? (
            <span className="vk-code-block__language">{title || language}</span>
          ) : <span />}
          {copyable && (
            <button
              className="vk-code-block__copy-btn"
              data-testid="code-block-copy-btn"
              aria-label={copied ? '已复制' : '复制代码'}
              onClick={handleCopy}
            >
              {copied ? copiedText : copyText}
            </button>
          )}
        </div>
      )}
      <div className="vk-code-block__body" style={{ maxHeight: scrollable ? maxHeight : undefined }}>
        {showLineNumbers ? (
          <div className="vk-code-block__lines">
            <div className="vk-code-block__line-numbers">
              {lineNumbers.map(n => (
                <span key={n} className="vk-code-block__line-number">{n}</span>
              ))}
            </div>
            <pre className={`vk-code-block__code${wrap ? ' vk-code-block__code--wrap' : ''}`}><code dangerouslySetInnerHTML={{ __html: highlightedHtml }} /></pre>
          </div>
        ) : (
          <pre className={`vk-code-block__code${wrap ? ' vk-code-block__code--wrap' : ''}`}><code dangerouslySetInnerHTML={{ __html: highlightedHtml }} /></pre>
        )}
      </div>
    </div>
  )
})

// src/vue/components/CodeBlock.vue
<template>
  <div class="vk-code-block" :class="{ 'vk-code-block--light': theme === 'light' }" data-testid="code-block">
    <div v-if="title || language || copyable" class="vk-code-block__header">
      <span v-if="title || language" class="vk-code-block__language">
        {{ title || language }}
      </span>
      <span v-else />
      <button
        v-if="copyable"
        class="vk-code-block__copy-btn"
        data-testid="code-block-copy-btn"
        :aria-label="copied ? '已复制' : '复制代码'"
        @click="handleCopy"
      >
        {{ copied ? copiedText : copyText }}
      </button>
    </div>
    <div class="vk-code-block__body" :style="{ maxHeight: scrollable ? maxHeight : undefined }">
      <div v-if="showLineNumbers" class="vk-code-block__lines">
        <div class="vk-code-block__line-numbers">
          <span v-for="n in lineNumbers" :key="n" class="vk-code-block__line-number">{{ n }}</span>
        </div>
        <pre class="vk-code-block__code" :class="{ 'vk-code-block__code--wrap': wrap }"><code v-html="highlightedHtml" /></pre>
      </div>
      <pre v-else class="vk-code-block__code" :class="{ 'vk-code-block__code--wrap': wrap }"><code v-html="highlightedHtml" /></pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue'
import type { CodeBlockProps } from '../../core/components/code-block.types'
import { copyToClipboard, generateLineNumbers, highlightCode, wrapLines } from '../../core/components/code-block.logic'
import '../../components/CodeBlock/style.css'

defineOptions({ name: 'VkCodeBlock' })

const props = withDefaults(defineProps<CodeBlockProps>(), {
  code: '',
  language: '',
  showLineNumbers: false,
  copyable: true,
  maxHeight: '500px',
  scrollable: true,
  wrap: false,
  copyText: '复制',
  copiedText: '已复制'
})

const copied = ref(false)
let copyTimer: ReturnType<typeof setTimeout> | null = null

const lineNumbers = computed(() => generateLineNumbers(props.code))
const highlightedHtml = computed(() => {
  const html = highlightCode(props.code, props.language)
  return props.highlightLines?.length ? wrapLines(html, props.highlightLines) : html
})

async function handleCopy() {
  try {
    await copyToClipboard(props.code)
    copied.value = true
    if (copyTimer) clearTimeout(copyTimer)
    copyTimer = setTimeout(() => { copied.value = false }, 2000)
  } catch {
    // clipboard API may fail in insecure contexts
  }
}

onUnmounted(() => {
  if (copyTimer) clearTimeout(copyTimer)
})
</script>
