// src/vue/components/Radio/Radio.vue
<template>
  <label
    class="vk-radio"
    :class="{
      'is-checked': isChecked,
      'is-disabled': isDisabled,
      [`vk-radio--${actualSize}`]: actualSize !== 'default'
    }"
  >
    <input
      class="vk-radio__input"
      type="radio"
      :name="actualName"
      :value="value"
      :disabled="isDisabled"
      :checked="isChecked"
      @change="handleChange"
    />
    <span class="vk-radio__inner"></span>
    <span class="vk-radio__label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import type { RadioProps, RadioEmits } from '../../../core/components/radio/types'
import { radioGroupContextKey } from '../../../core/components/radio/types'
import '@/components/Radio/style.css'

defineOptions({ name: 'VkRadio' })

const props = defineProps<RadioProps>()
const emits = defineEmits<RadioEmits>()

const radioGroup = inject(radioGroupContextKey, undefined)

const isChecked = computed(() => {
  if (radioGroup) {
    return radioGroup.modelValue === props.value
  }
  return props.modelValue === props.value
})

const isDisabled = computed(() => radioGroup?.disabled || props.disabled)
const actualSize = computed(() => radioGroup?.size || props.size || 'default')
const actualName = computed(() => radioGroup?.name || props.name)

const handleChange = () => {
  if (isDisabled.value) return
  if (radioGroup) {
    radioGroup.handleChange(props.value)
  } else {
    emits('update:modelValue', props.value)
    emits('change', props.value)
  }
}
</script>

// src/react/components/Radio/Radio.tsx
import { memo, useContext, createContext } from 'react'
import type { RadioProps, RadioGroupProps, RadioGroupContext, RadioValueType } from '../../../core/components/radio/types'
import '../../../components/Radio/style.css'

const RadioGroupContextReact = createContext<RadioGroupContext | null>(null)

export function RadioGroup({
  modelValue,
  disabled,
  name,
  size,
  children,
  onChange,
}: RadioGroupProps) {
  const handleChange = (value: RadioValueType) => {
    onChange?.(value)
  }

  return (
    <RadioGroupContextReact.Provider value={{ modelValue, disabled, name, size, handleChange }}>
      <div className="vk-radio-group">{children}</div>
    </RadioGroupContextReact.Provider>
  )
}

export const Radio = memo(function Radio({
  value,
  label,
  disabled,
  name,
  size,
  modelValue,
  children,
}: RadioProps & { onChange?: (value: RadioValueType) => void }) {
  const group = useContext(RadioGroupContextReact)

  const isChecked = group ? group.modelValue === value : modelValue === value
  const isDisabled = group?.disabled || disabled
  const actualSize = group?.size || size || 'default'
  const actualName = group?.name || name

  const handleChange = () => {
    if (isDisabled) return
    if (group) {
      group.handleChange(value)
    }
  }

  const classes = [
    'vk-radio',
    isChecked ? 'is-checked' : '',
    isDisabled ? 'is-disabled' : '',
    actualSize !== 'default' ? `vk-radio--${actualSize}` : '',
  ].filter(Boolean).join(' ')

  return (
    <label className={classes}>
      <input
        className="vk-radio__input"
        type="radio"
        name={actualName}
        value={String(value)}
        disabled={isDisabled}
        checked={isChecked}
        onChange={handleChange}
      />
      <span className="vk-radio__inner" />
      <span className="vk-radio__label">{children ?? label}</span>
    </label>
  )
})
