// src/vue/components/Checkbox/Checkbox.vue
<template>
  <label
    class="vk-checkbox"
    :class="{
      'is-checked': isChecked,
      'is-disabled': isDisabled
    }"
  >
    <input
      class="vk-checkbox__input"
      type="checkbox"
      :name="name"
      :disabled="isDisabled"
      :checked="isChecked"
      @change="handleChange"
    />
    <span class="vk-checkbox__inner"></span>
    <span class="vk-checkbox__label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import type { CheckboxProps, CheckboxEmits, CheckboxValueType } from '../../../core/components/checkbox/types'
import { checkboxGroupContextKey } from '../../../core/components/checkbox/types'
import '../../../components/Checkbox/style.css'

defineOptions({ name: 'VkCheckbox' })

const props = defineProps<CheckboxProps>()
const emits = defineEmits<CheckboxEmits>()

const checkboxGroup = inject(checkboxGroupContextKey, undefined)

const isChecked = computed(() => {
  if (checkboxGroup && props.value !== undefined) {
    return checkboxGroup.modelValue.includes(props.value)
  }
  return props.modelValue ?? props.checked ?? false
})

const isDisabled = computed(() => {
  if (checkboxGroup) {
    if (checkboxGroup.disabled) return true
    if (!isChecked.value && checkboxGroup.max !== undefined && checkboxGroup.modelValue.length >= checkboxGroup.max) return true
    if (isChecked.value && checkboxGroup.min !== undefined && checkboxGroup.modelValue.length <= checkboxGroup.min) return true
  }
  return props.disabled ?? false
})

const handleChange = () => {
  if (isDisabled.value) return
  if (checkboxGroup && props.value !== undefined) {
    checkboxGroup.handleChange(props.value, !isChecked.value)
  } else {
    const newVal = !isChecked.value
    emits('update:modelValue', newVal)
    emits('change', newVal)
  }
}
</script>

// src/react/components/Checkbox/Checkbox.tsx
import { memo, useContext, createContext } from 'react'
import type { CheckboxProps, CheckboxGroupProps, CheckboxGroupContext, CheckboxValueType } from '../../../core/components/checkbox/types'
import '../../../components/Checkbox/style.css'

const CheckboxGroupContextReact = createContext<CheckboxGroupContext | null>(null)

export function CheckboxGroup({
  modelValue,
  disabled,
  min,
  max,
  children,
  onChange,
}: CheckboxGroupProps) {
  const handleChange = (value: CheckboxValueType, checked: boolean) => {
    const newVal = [...modelValue]
    if (checked) {
      if (max !== undefined && newVal.length >= max) return
      newVal.push(value)
    } else {
      if (min !== undefined && newVal.length <= min) return
      const idx = newVal.indexOf(value)
      if (idx > -1) newVal.splice(idx, 1)
    }
    onChange?.(newVal)
  }

  return (
    <CheckboxGroupContextReact.Provider value={{ modelValue, disabled, min, max, handleChange }}>
      <div className="vk-checkbox-group">{children}</div>
    </CheckboxGroupContextReact.Provider>
  )
}

export const Checkbox = memo(function Checkbox({
  value,
  label,
  disabled,
  checked,
  name,
  modelValue,
  children,
}: CheckboxProps & { onChange?: (checked: boolean) => void }) {
  const group = useContext(CheckboxGroupContextReact)

  const isChecked = group && value !== undefined
    ? group.modelValue.includes(value)
    : (modelValue ?? checked ?? false)

  const isDisabled = (() => {
    if (group) {
      if (group.disabled) return true
      if (!isChecked && group.max !== undefined && group.modelValue.length >= group.max) return true
      if (isChecked && group.min !== undefined && group.modelValue.length <= group.min) return true
    }
    return disabled ?? false
  })()

  const handleChange = () => {
    if (isDisabled) return
    if (group && value !== undefined) {
      group.handleChange(value, !isChecked)
    }
  }

  const classes = [
    'vk-checkbox',
    isChecked ? 'is-checked' : '',
    isDisabled ? 'is-disabled' : '',
  ].filter(Boolean).join(' ')

  return (
    <label className={classes}>
      <input
        className="vk-checkbox__input"
        type="checkbox"
        name={name}
        disabled={isDisabled}
        checked={!!isChecked}
        onChange={handleChange}
      />
      <span className="vk-checkbox__inner" />
      <span className="vk-checkbox__label">{children ?? label}</span>
    </label>
  )
})
