// src/react/components/Select/Select.tsx
import React, { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { debounce } from 'lodash-es';
import type {
  SelectProps,
  SelectOption,
} from '../../../core/components/select.react.types';
import Input from '../Input';
import type { InputRef } from '../../../core/components/input.react.types';
import Icon from '../Icon';
import '../../../components/Select/style.css';

export default function Select({
  modelValue,
  options = [],

  placeholder,
  disabled = false,
  clearable = false,
  renderLabel,
  filterable = false,
  filterMethod,
  remote = false,
  remoteMethod,
  onChange,
  'onUpdate:modelValue': onUpdateModelValue,
  onVisibleChange,
  onClear,
}: SelectProps) {
  const findOption = (value: string) => options.find((o) => o.value === value) ?? null;

  const initialOption = findOption(modelValue);
  const [inputValue, setInputValue] = useState(initialOption ? initialOption.label : '');
  const [selectedOption, setSelectedOption] = useState<SelectOption | null>(initialOption);
  const [mouseHover, setMouseHover] = useState(false);
  const [loading, setLoading] = useState(false);
  const [highlightIndex, setHighlightIndex] = useState(-1);
  const [isDropdownShow, setIsDropdownShow] = useState(false);
  const [filteredOptions, setFilteredOptions] = useState<SelectOption[]>(options);

  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<InputRef>(null);

  // Sync options prop changes
  useEffect(() => {
    setFilteredOptions(options);
  }, [options]);

  const timeout = remote ? 300 : 0;

  const generateFilterOptions = useCallback(
    async (searchValue: string) => {
      if (!filterable) return;
      if (filterMethod && typeof filterMethod === 'function') {
        setFilteredOptions(filterMethod(searchValue));
      } else if (remote && remoteMethod && typeof remoteMethod === 'function') {
        setLoading(true);
        try {
          const result = await remoteMethod(searchValue);
          setFilteredOptions(result);
        } catch (e) {
          console.error(e);
          setFilteredOptions([]);
        } finally {
          setLoading(false);
        }
      } else {
        setFilteredOptions(options.filter((o) => o.label.includes(searchValue)));
      }
      setHighlightIndex(-1);
    },
    [filterable, filterMethod, remote, remoteMethod, options]
  );

  const debouncedFilter = useMemo(
    () => debounce((val: string) => generateFilterOptions(val), timeout),
    [generateFilterOptions, timeout]
  );

  const controlDropdown = useCallback(
    (show: boolean, currentInputValue?: string, currentSelectedOption?: SelectOption | null) => {
      if (show) {
        if (filterable && currentSelectedOption) {
          setInputValue('');
        }
        if (filterable) {
          generateFilterOptions(filterable && currentSelectedOption ? '' : (currentInputValue ?? ''));
        }
      } else {
        if (filterable) {
          setInputValue(currentSelectedOption ? currentSelectedOption.label : '');
        }
        setHighlightIndex(-1);
      }
      setIsDropdownShow(show);
      onVisibleChange?.(show);
    },
    [filterable, generateFilterOptions, onVisibleChange]
  );

  // Click-outside detection
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        if (isDropdownShow) {
          controlDropdown(false, inputValue, selectedOption);
        }
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isDropdownShow, controlDropdown, inputValue, selectedOption]);

  const toggleDropdown = () => {
    if (disabled) return;
    if (isDropdownShow) {
      controlDropdown(false, inputValue, selectedOption);
    } else {
      controlDropdown(true, inputValue, selectedOption);
    }
  };

  const itemSelect = (item: SelectOption) => {
    if (item.disabled) return;
    setInputValue(item.label);
    setSelectedOption(item);
    onChange?.(item.value);
    onUpdateModelValue?.(item.value);
    setIsDropdownShow(false);
    setHighlightIndex(-1);
    onVisibleChange?.(false);
    inputRef.current?.ref?.focus();
  };

  const showClearIcon = clearable && mouseHover && selectedOption && inputValue.trim() !== '';

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation();
    setSelectedOption(null);
    setInputValue('');
    onClear?.();
    onChange?.('');
    onUpdateModelValue?.('');
  };

  const handleInputChange = (val: string) => {
    setInputValue(val);
    debouncedFilter(val);
  };

  const filteredPlaceholder =
    filterable && selectedOption && isDropdownShow ? selectedOption.label : placeholder;

  const handleKeyDown = (e: React.KeyboardEvent) => {
    switch (e.key) {
      case 'Enter':
        if (!isDropdownShow) {
          controlDropdown(true, inputValue, selectedOption);
        } else {
          if (highlightIndex > -1 && filteredOptions[highlightIndex]) {
            itemSelect(filteredOptions[highlightIndex]);
          } else {
            controlDropdown(false, inputValue, selectedOption);
          }
        }
        break;
      case 'Escape':
        if (isDropdownShow) {
          controlDropdown(false, inputValue, selectedOption);
        }
        break;
      case 'ArrowUp':
        e.preventDefault();
        if (filteredOptions.length > 0) {
          if (highlightIndex === -1 || highlightIndex === 0) {
            setHighlightIndex(filteredOptions.length - 1);
          } else {
            setHighlightIndex(highlightIndex - 1);
          }
        }
        break;
      case 'ArrowDown':
        e.preventDefault();
        if (filteredOptions.length > 0) {
          if (highlightIndex === -1 || highlightIndex === filteredOptions.length - 1) {
            setHighlightIndex(0);
          } else {
            setHighlightIndex(highlightIndex + 1);
          }
        }
        break;
      default:
        break;
    }
  };

  const NOOP = (e: React.MouseEvent) => {
    e.preventDefault();
  };

  return (
    <div
      className={`vk-select${disabled ? ' is-disabled' : ''}`}
      ref={containerRef}
      onClick={toggleDropdown}
      onMouseEnter={() => setMouseHover(true)}
      onMouseLeave={() => setMouseHover(false)}
    >
      <Input
        modelValue={inputValue}
        disabled={disabled}
        placeholder={filteredPlaceholder}
        ref={inputRef}
        readonly={!filterable || !isDropdownShow}
        onInput={handleInputChange}
        onUpdate:modelValue={handleInputChange}
        onKeyDown={handleKeyDown}
        suffix={
          showClearIcon ? (
            <Icon
              name="circle-xmark"
              className="vk-input__clear"
              onMouseDown={NOOP}
              onClick={handleClear}
            />
          ) : (
            <Icon
              name="angle-down"
              className={`header-angle${isDropdownShow ? ' is-active' : ''}`}
            />
          )
        }
      />
      {isDropdownShow && (
        <div style={{ position: 'absolute', top: '100%', left: 0, width: '100%', zIndex: 9999 }}>
          {loading ? (
            <div className="vk-select__loading">
              <Icon name="spinner" spin />
            </div>
          ) : filterable && filteredOptions.length === 0 ? (
            <div className="vk-select__nodata">no matching data</div>
          ) : (
            <ul className="vk-select__menu">
              {filteredOptions.map((item, index) => (
                <li
                  key={item.value}
                  className={[
                    'vk-select__menu-item',
                    item.disabled ? 'is-disabled' : '',
                    selectedOption?.value === item.value ? 'is-selected' : '',
                    highlightIndex === index ? 'is-highlighted' : '',
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  id={`select-item-${item.value}`}
                  onClick={(e) => {
                    e.stopPropagation();
                    itemSelect(item);
                  }}
                >
                  {renderLabel ? renderLabel(item) : item.label}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

// src/components/Select/Select.vue
<template>
<div
  class="vk-select"
  :class="{'is-disabled': disabled }"
  @click="toggleDropdown"
  @mouseenter="states.mouseHover = true"
  @mouseleave="states.mouseHover = false"
>
  <Tooltip
    placement="bottom-start"
    ref="tooltipRef"
    :popperOptions="popperOptions"
    @click-outside="controlDropdown(false)"
    manual
  >
    <Input 
      v-model="states.inputValue"
      :disabled="disabled"
      :placeholder="filteredPlaceholder"
      ref="inputRef"
      :readonly="!filterable || !isDropdownShow"
      @input="debouceOnFilter"
      @keydown="handleKeydown"
    >
      <template #suffix>
        <Icon 
          icon="circle-xmark"
          v-if="showClearIcon"
          class="vk-input__clear"
          @mousedown.prevent="NOOP"
          @click.stop="onClear"  
        />

        <Icon
          v-else
          icon="angle-down" 
          class="header-angle" 
          :class="{ 'is-active': isDropdownShow }"
        />
      </template>
    </Input>
    <template #content>
      <div class="vk-select__loading" v-if="states.loading"><Icon icon="spinner" spin/></div>
      <div class="vk-select__nodata" v-else-if="filterable && filteredOptions.length === 0">no matching data</div>
      <ul class="vk-select__menu" v-else>
        <template v-for="(item, index) in filteredOptions" :key="index">
          <li 
            class="vk-select__menu-item"
            :class="{
              'is-disabled': item.disabled, 
              'is-selected': states.selectedOption?.value === item.value ,
              'is-highlighted': states.highlightIndex === index
            }"
            :id="`select-item-${item.value}`"
            @click.stop="itemSelect(item)"
          >
            <RenderVnode :vNode="renderLabel ? renderLabel(item) : item.label"/>
          </li>
        </template>
      </ul>
    </template>
  </Tooltip>
</div>  
</template>
<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import type { Ref } from 'vue'
import { isFunction, debounce } from 'lodash-es'
import type { SelectProps, SelectEmits, SelectOption, SelectStates } from './types'
import Tooltip from '../Tooltip/Tooltip.vue'
import type { TooltipInstance } from '../Tooltip/types'
import Input from '../Input/Input.vue'
import Icon from '../Icon/Icon.vue'
import RenderVnode from '../Common/RenderVnode'
import type { InputInstance } from '../Input/types'

const findOption = (value: string) => {
  const option = props.options.find(option => option.value === value)
  return option ? option : null
}
defineOptions({
  name: 'VkSelect'
})
const props = withDefaults(defineProps<SelectProps>(), {
  options: () => []
})
const timeout = computed(() => props.remote ? 300 : 0)
const emits = defineEmits<SelectEmits>()
const initialOption = findOption(props.modelValue)
const tooltipRef = ref() as Ref<TooltipInstance>
const inputRef = ref() as Ref<InputInstance>
const states = reactive<SelectStates>({
  inputValue: initialOption ? initialOption.label : '',
  selectedOption: initialOption,
  mouseHover: false,
  loading: false,
  highlightIndex: -1
})
const isDropdownShow = ref(false)
const popperOptions: any = {
  modifiers: [
    {
      name: 'offset',
      options: {
        offset: [0, 9],
      },
    },
    {
      name: "sameWidth",
      enabled: true,
      fn: ({ state }: { state: any }) => {
          state.styles.popper.width = `${state.rects.reference.width}px`;
      },
      phase: "beforeWrite",
      requires: ["computeStyles"],
    }
  ],
}
const filteredOptions = ref(props.options)
watch(() => props.options, (newOptions) => {
  filteredOptions.value = newOptions
})
const generateFilterOptions = async (searchValue: string) => {
  if (!props.filterable) return
  if (props.filterMethod && isFunction(props.filterMethod)) {
    filteredOptions.value = props.filterMethod(searchValue)
  } else if (props.remote && props.remoteMethod && isFunction(props.remoteMethod)) {
    states.loading = true
    try {
      filteredOptions.value = await props.remoteMethod(searchValue)
    } catch (e) {
      console.error(e)
      filteredOptions.value = []
    } finally {
      states.loading = false
    }
  } else {
    filteredOptions.value = props.options.filter(option => option.label.includes(searchValue))
  }
  states.highlightIndex = -1

}
const onFilter = () => {
  generateFilterOptions(states.inputValue)
}
const debouceOnFilter = debounce(() => {
  onFilter()
}, timeout.value)
const filteredPlaceholder = computed(() => {
  return (props.filterable && states.selectedOption && isDropdownShow.value) 
  ? states.selectedOption.label : props.placeholder
})
const controlDropdown = (show: boolean) => {
  if (show) {
    // filter 模式
    // 之前选择过对应的值
    if (props.filterable && states.selectedOption) {
      states.inputValue = ''
    }
    // 进行一次默认选项的生成
    if (props.filterable) {
      generateFilterOptions(states.inputValue)
    }
    tooltipRef.value.show()
  } else {
    tooltipRef.value.hide()
    // blur 时候将之前的值回灌到 input 中
    if (props.filterable) {
      states.inputValue = states.selectedOption ? states.selectedOption.label : ''
    }
    states.highlightIndex = -1
  }
  isDropdownShow.value = show
  emits('visible-change', show)
}
const handleKeydown = (e: KeyboardEvent) => {
  switch (e.key) {
    case 'Enter':
      if (!isDropdownShow.value) {
        controlDropdown(true)
      } else {
        if (states.highlightIndex > -1 && filteredOptions.value[states.highlightIndex]) {
          itemSelect(filteredOptions.value[states.highlightIndex])
        } else {
          controlDropdown(false)
        }
      }
      break
    case 'Escape':
      if (isDropdownShow.value) {
        controlDropdown(false)
      }
      break
    case 'ArrowUp':
      e.preventDefault()
      // states.highlightIndex = -1
      if (filteredOptions.value.length > 0) {
        if (states.highlightIndex === -1 || states.highlightIndex === 0) {
          states.highlightIndex = filteredOptions.value.length - 1
        } else {
          // move up
          states.highlightIndex--
        }
      }
      break
    case 'ArrowDown':
      e.preventDefault()
      // states.highlightIndex = -1
      if (filteredOptions.value.length > 0) {
        if (states.highlightIndex === -1 || states.highlightIndex === (filteredOptions.value.length - 1)) {
          states.highlightIndex = 0
        } else {
          // move up
          states.highlightIndex++
        }
      }
      break
    default:
      break;
  }
}
const showClearIcon = computed(() => {
  // * hover 上去
  // * props.clearable 为 true
  // 必须要有选择过选项
  // Input 的值不能为空
  return props.clearable 
    && states.mouseHover
    && states.selectedOption
    && states.inputValue.trim() !== ''
})
const onClear = () => {
  states.selectedOption = null
  states.inputValue = ''
  emits('clear')
  emits('change', '')
  emits('update:modelValue', '')
}
const NOOP = () => {}
const toggleDropdown = () => {
  if (props.disabled) return
  if (isDropdownShow.value) {
    controlDropdown(false)
  } else {
    controlDropdown(true)
  }
}
const itemSelect = (e: SelectOption) => {
  if (e.disabled) return
  states.inputValue = e.label
  states.selectedOption = e
  emits('change', e.value)
  emits('update:modelValue', e.value)
  controlDropdown(false)
  inputRef.value.ref.focus()
}
</script>
