// src/react/components/Modal/Modal.tsx
import { useEffect, useCallback } from 'react'
import type { ModalProps } from '../../../core/components/modal.react.types'
import Icon from '../Icon'
import '../../../components/Modal/style.css'

export function Modal({
  visible,
  title,
  width = '520px',
  top = '15vh',
  closable = true,
  maskClosable = true,
  showFooter = true,
  children,
  footer,
  onClose,
  onConfirm,
  onCancel,
  onOpen,
}: ModalProps) {
  useEffect(() => {
    if (visible) {
      onOpen?.()
    }
  }, [visible])

  const handleClose = useCallback(() => {
    onClose?.()
  }, [onClose])

  const handleMaskClick = useCallback(() => {
    if (maskClosable) handleClose()
  }, [maskClosable, handleClose])

  const handleConfirm = useCallback(() => {
    onConfirm?.()
    handleClose()
  }, [onConfirm, handleClose])

  const handleCancel = useCallback(() => {
    onCancel?.()
    handleClose()
  }, [onCancel, handleClose])

  if (!visible) return null

  return (
    <div className="vk-overlay" onClick={handleMaskClick}>
      <div
        className="vk-modal"
        style={{ width, marginTop: top }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="vk-modal__header">
          <span className="vk-modal__title">{title}</span>
          {closable && (
            <button className="vk-modal__close" onClick={handleClose}>
              <Icon name="xmark" />
            </button>
          )}
        </div>
        <div className="vk-modal__body">{children}</div>
        {showFooter && (
          <div className="vk-modal__footer">
            {footer ?? (
              <>
                <button className="vk-button" onClick={handleCancel}>取消</button>
                <button className="vk-button vk-button--primary" onClick={handleConfirm}>确定</button>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

// src/vue/components/Modal/Modal.vue
<template>
  <Teleport to="body">
    <Transition name="vk-modal-fade">
      <div
        v-if="modelValue"
        class="vk-overlay"
        @click.self="handleMaskClick"
      >
        <div
          class="vk-modal"
          :style="{ width: width, marginTop: top }"
        >
          <div class="vk-modal__header">
            <span class="vk-modal__title">
              <slot name="title">{{ title }}</slot>
            </span>
            <button
              v-if="closable"
              class="vk-modal__close"
              @click="handleClose"
            >
              <Icon icon="xmark" />
            </button>
          </div>
          <div class="vk-modal__body">
            <slot />
          </div>
          <div v-if="showFooter" class="vk-modal__footer">
            <slot name="footer">
              <Button @click="handleCancel">取消</Button>
              <Button type="primary" @click="handleConfirm">确定</Button>
            </slot>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { watch } from 'vue'
import type { ModalProps, ModalEmits } from '../../../core/components/modal.types'
import Icon from '../Icon.vue'
import Button from '../Button.vue'
import '../../../components/Modal/style.css'

defineOptions({ name: 'VkModal' })

const props = withDefaults(defineProps<ModalProps>(), {
  width: '520px',
  top: '15vh',
  closable: true,
  maskClosable: true,
  showFooter: true
})

const emits = defineEmits<ModalEmits>()

watch(() => props.modelValue, (val) => {
  if (val) {
    emits('open')
  }
})

const handleClose = () => {
  emits('update:modelValue', false)
  emits('close')
}

const handleMaskClick = () => {
  if (props.maskClosable) {
    handleClose()
  }
}

const handleConfirm = () => {
  emits('confirm')
  handleClose()
}

const handleCancel = () => {
  emits('cancel')
  handleClose()
}
</script>
