// src/vue/components/Collapse/CollapseItem.vue
<template>
  <div
      class="vk-collapse-item"
      :class="{
    'is-disabled': disabled
  }"
  >
    <div
        class="vk-collapse-item__header"
        :class="{
      'is-disabled': disabled,
      'is-active': isActive
    }"
        :id="`item-header-${name}`"
        @click="handleClick"
    >
      <slot name="title">{{title}}</slot>
      <Icon icon="angle-right" class="header-angle" />
    </div>
    <Transition name="slide" v-on="transitionEvents">
      <div class="vk-collapse-item__wrapper" v-show="isActive">
        <div class="vk-collapse-item__content" :id="`item-content-${name}`">
          <slot/>
        </div>
      </div>
    </Transition>
  </div>
</template>
<script setup lang="ts">
import { inject, computed } from 'vue'
import type { CollapseItemProps } from '../../../core/components/collapse/types'
import { collapseContextKey } from '../../../core/components/collapse/types'
import Icon from '../Icon.vue'
defineOptions({
  name: 'VkCollapseItem'
})
const props = defineProps<CollapseItemProps>()
const collapseContext = inject(collapseContextKey)
const isActive = computed(() => collapseContext?.activeNames.value.includes(props.name))
const handleClick = () => {
  if (props.disabled) { return }
  collapseContext?.handleItemClick(props.name)
}
const transitionEvents: Record<string, (el: HTMLElement) => void> = {
  beforeEnter(el) {
    el.style.height = '0px'
    el.style.overflow = 'hidden'
  },
  enter(el) {
    el.style.height = `${el.scrollHeight}px`
  },
  afterEnter(el) {
    el.style.height = ''
    el.style.overflow = ''
  },
  beforeLeave(el) {
    el.style.height = `${el.scrollHeight}px`
    el.style.overflow = 'hidden'
  },
  leave(el) {
    el.style.height = '0px'
  },
  afterLeave(el) {
    el.style.height = ''
    el.style.overflow = ''
  }

}
</script>

// src/react/components/Collapse/CollapseItem.tsx
import React from 'react'
import { useCollapseContext } from './Collapse'
import type { CollapseItemProps } from '../../../core/components/collapse/types'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faAngleRight } from '@fortawesome/free-solid-svg-icons'

export const CollapseItem: React.FC<CollapseItemProps> = ({
                                                              name,
                                                              title,
                                                              disabled,
                                                              children
                                                          }) => {
    const { activeNames, handleItemClick } = useCollapseContext()
    const isActive = activeNames.includes(name)

    const onClick = () => {
        if (!disabled) handleItemClick(name)
    }

    return (
        <div className={`vk-collapse-item ${disabled ? 'is-disabled' : ''}`}>
            <div
                className={`vk-collapse-item__header ${isActive ? 'is-active' : ''}`}
                onClick={onClick}
            >
                <span>{title}</span>
                <FontAwesomeIcon
                    icon={faAngleRight}
                    className={`header-angle ${isActive ? 'rotate-90' : ''}`}
                />
            </div>

            {isActive && (
                <div className="vk-collapse-item__wrapper">
                    <div className="vk-collapse-item__content">{children}</div>
                </div>
            )}
        </div>
    )
}
