// src/react/components/Tabs/TabPane.tsx
import { memo } from 'react'
import type { TabPaneProps } from '../../../core/components/tabs/types'
import { useTabsContext } from './Tabs'

export const TabPane = memo(function TabPane({
  name,
  children,
}: TabPaneProps) {
  const { activeName } = useTabsContext()

  if (activeName !== name) return null

  return (
    <div className="vk-tabs__pane is-active">
      {children}
    </div>
  )
})

// src/vue/components/Tabs/TabPane.vue
<template>
  <div
    class="vk-tabs__pane"
    :class="{ 'is-active': isActive }"
    v-show="isActive"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { inject, computed, onMounted, onBeforeUnmount } from 'vue'
import type { TabPaneProps } from '../../../core/components/tabs/types'

defineOptions({ name: 'VkTabPane' })

const props = defineProps<TabPaneProps>()

const addPane = inject<(pane: TabPaneProps) => void>('vk-tabs-add-pane')
const removePane = inject<(name: string | number) => void>('vk-tabs-remove-pane')
const getActiveName = inject<() => string | number>('vk-tabs-active-name')

const isActive = computed(() => getActiveName?.() === props.name)

onMounted(() => {
  addPane?.({
    name: props.name,
    label: props.label,
    disabled: props.disabled
  })
})

onBeforeUnmount(() => {
  removePane?.(props.name)
})
</script>
