// src/react/components/Tabs/Tabs.tsx
import { createContext, useContext, Children, isValidElement } from 'react'
import type { TabsProps, TabsContext, TabPaneProps } from '../../../core/components/tabs/types'
import '../../../components/Tabs/style.css'

const TabsContextReact = createContext<TabsContext | null>(null)

export const useTabsContext = () => {
  const ctx = useContext(TabsContextReact)
  if (!ctx) throw new Error('TabPane must be used inside Tabs')
  return ctx
}

export function Tabs({
  modelValue,
  type = 'line',
  children,
  onChange,
}: TabsProps) {
  const handleTabClick = (name: string | number) => {
    onChange?.(name)
  }

  const panes: { name: string | number; label: string; disabled?: boolean }[] = []
  Children.forEach(children, (child) => {
    if (isValidElement<TabPaneProps>(child) && child.props.name !== undefined) {
      panes.push({
        name: child.props.name,
        label: child.props.label,
        disabled: child.props.disabled,
      })
    }
  })

  return (
    <TabsContextReact.Provider value={{ activeName: modelValue, handleTabClick }}>
      <div className={`vk-tabs ${type === 'card' ? 'vk-tabs--card' : ''}`}>
        <div className="vk-tabs__header">
          {panes.map((pane) => (
            <div
              key={String(pane.name)}
              className={`vk-tabs__item ${modelValue === pane.name ? 'is-active' : ''} ${pane.disabled ? 'is-disabled' : ''}`}
              onClick={() => !pane.disabled && handleTabClick(pane.name)}
            >
              {pane.label}
            </div>
          ))}
        </div>
        <div className="vk-tabs__content">{children}</div>
      </div>
    </TabsContextReact.Provider>
  )
}

// src/vue/components/Tabs/Tabs.vue
<template>
  <div
    class="vk-tabs"
    :class="{ 'vk-tabs--card': type === 'card' }"
  >
    <div class="vk-tabs__header">
      <div
        v-for="pane in paneList"
        :key="pane.name"
        class="vk-tabs__item"
        :class="{
          'is-active': modelValue === pane.name,
          'is-disabled': pane.disabled
        }"
        @click="handleTabClick(pane)"
      >
        {{ pane.label }}
      </div>
    </div>
    <div class="vk-tabs__content">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, provide, watch, onMounted } from 'vue'
import type { TabsProps, TabsEmits, TabPaneProps } from '../../../core/components/tabs/types'
import { tabsContextKey } from '../../../core/components/tabs/types'
import '@/components/Tabs/style.css'

defineOptions({ name: 'VkTabs' })

const props = withDefaults(defineProps<TabsProps>(), {
  type: 'line'
})
const emits = defineEmits<TabsEmits>()

const paneList = ref<TabPaneProps[]>([])

const addPane = (pane: TabPaneProps) => {
  paneList.value.push(pane)
}

const removePane = (name: string | number) => {
  const index = paneList.value.findIndex(p => p.name === name)
  if (index > -1) paneList.value.splice(index, 1)
}

const handleTabClick = (pane: TabPaneProps) => {
  if (pane.disabled) return
  emits('update:modelValue', pane.name)
  emits('change', pane.name)
}

provide(tabsContextKey, {
  activeName: props.modelValue,
  handleTabClick: (name: string | number) => {
    emits('update:modelValue', name)
    emits('change', name)
  }
})

provide('vk-tabs-add-pane', addPane)
provide('vk-tabs-remove-pane', removePane)
provide('vk-tabs-active-name', () => props.modelValue)
</script>
