// src/vue/components/Tag/Tag.vue
<template>
  <span
    v-if="visible"
    class="vk-tag"
    :class="[
      type ? `vk-tag--${type}` : '',
      size && size !== 'default' ? `vk-tag--${size}` : '',
      effect ? `vk-tag--${effect}` : 'vk-tag--light',
      { 'is-round': round }
    ]"
    :style="color ? { backgroundColor: color, borderColor: color, color: '#fff' } : {}"
    @click="handleClick"
  >
    <span class="vk-tag__content">
      <slot />
    </span>
    <button
      v-if="closable"
      class="vk-tag__close"
      @click.stop="handleClose"
    >
      <Icon icon="xmark" />
    </button>
  </span>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { TagProps, TagEmits } from '../../../core/components/tag.types'
import Icon from '../Icon.vue'
import '../../../components/Tag/style.css'

defineOptions({ name: 'VkTag' })

withDefaults(defineProps<TagProps>(), {
  type: 'primary',
  size: 'default',
  effect: 'light',
  closable: false,
  round: false
})

const emits = defineEmits<TagEmits>()
const visible = ref(true)

const handleClose = () => {
  visible.value = false
  emits('close')
}

const handleClick = () => {
  emits('click')
}
</script>

// src/react/components/Tag/Tag.tsx
import { useState, memo } from 'react'
import type { TagProps } from '../../../core/components/tag.react.types'
import Icon from '../Icon'
import '../../../components/Tag/style.css'

export const Tag = memo(function Tag({
  type = 'primary',
  size = 'default',
  effect = 'light',
  closable = false,
  round = false,
  color,
  children,
  onClose,
  onClick,
}: TagProps) {
  const [visible, setVisible] = useState(true)

  if (!visible) return null

  const classes = [
    'vk-tag',
    type ? `vk-tag--${type}` : '',
    size !== 'default' ? `vk-tag--${size}` : '',
    effect ? `vk-tag--${effect}` : '',
    round ? 'is-round' : '',
  ].filter(Boolean).join(' ')

  const style = color
    ? { backgroundColor: color, borderColor: color, color: '#fff' }
    : undefined

  const handleClose = (e: React.MouseEvent) => {
    e.stopPropagation()
    setVisible(false)
    onClose?.()
  }

  return (
    <span className={classes} style={style} onClick={onClick}>
      <span className="vk-tag__content">{children}</span>
      {closable && (
        <button className="vk-tag__close" onClick={handleClose}>
          <Icon name="xmark" />
        </button>
      )}
    </span>
  )
})
